/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 🐺 Werewolf Betting Game API
 * API for Werewolf Betting Game with auto-play mode. WebSocket namespace: /game
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AdminActionResponseDto,
  BetRequestDto,
  BetResponseDto,
  CreateUserDto,
  CreateUserResponseDto,
  GameHistoryResponseDto,
  GameProgressResponseDto,
  GameStatsResponseDto,
  GameStatusResponseDto,
  GetHistoryParams,
  UserBalanceResponseDto,
} from "./models";

import { customClient } from "./custom-client";
import type { ErrorType, BodyType } from "./custom-client";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const healthCheck = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<void>(
    { url: `/api/health-check`, method: "GET", signal },
    options,
  );
};

export const getHealthCheckQueryKey = () => {
  return [`/api/health-check`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck(requestOptions, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Create a new user with optional custom ID, username and initial balance
 * @summary Create a new user
 */
export const create = (
  createUserDto: BodyType<CreateUserDto>,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<CreateUserResponseDto>(
    {
      url: `/api/users`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createUserDto,
      signal,
    },
    options,
  );
};

export const getCreateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof create>>,
    TError,
    { data: BodyType<CreateUserDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof create>>,
  TError,
  { data: BodyType<CreateUserDto> },
  TContext
> => {
  const mutationKey = ["create"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof create>>,
    { data: BodyType<CreateUserDto> }
  > = (props) => {
    const { data } = props ?? {};

    return create(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof create>>
>;
export type CreateMutationBody = BodyType<CreateUserDto>;
export type CreateMutationError = ErrorType<void>;

/**
 * @summary Create a new user
 */
export const useCreate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof create>>,
    TError,
    { data: BodyType<CreateUserDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationResult<
  Awaited<ReturnType<typeof create>>,
  TError,
  { data: BodyType<CreateUserDto> },
  TContext
> => {
  const mutationOptions = getCreateMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * Retrieve a list of all registered users
 * @summary Get all users
 */
export const findAll = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<CreateUserResponseDto[]>(
    { url: `/api/users`, method: "GET", signal },
    options,
  );
};

export const getFindAllQueryKey = () => {
  return [`/api/users`] as const;
};

export const getFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof findAll>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof findAll>>, TError, TData>;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindAllQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findAll>>> = ({
    signal,
  }) => findAll(requestOptions, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof findAll>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type FindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof findAll>>
>;
export type FindAllQueryError = ErrorType<unknown>;

/**
 * @summary Get all users
 */

export function useFindAll<
  TData = Awaited<ReturnType<typeof findAll>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof findAll>>, TError, TData>;
  request?: SecondParameter<typeof customClient>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getFindAllQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Retrieve a specific user by their ID
 * @summary Get user by ID
 */
export const findById = (
  id: string,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<CreateUserResponseDto>(
    { url: `/api/users/${id}`, method: "GET", signal },
    options,
  );
};

export const getFindByIdQueryKey = (id?: string) => {
  return [`/api/users/${id}`] as const;
};

export const getFindByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof findById>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof findById>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findById>>> = ({
    signal,
  }) => findById(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof findById>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type FindByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof findById>>
>;
export type FindByIdQueryError = ErrorType<void>;

/**
 * @summary Get user by ID
 */

export function useFindById<
  TData = Awaited<ReturnType<typeof findById>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof findById>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getFindByIdQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Retrieve the current balance of a specific user
 * @summary Get user balance
 */
export const getBalance = (
  id: string,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<UserBalanceResponseDto>(
    { url: `/api/users/${id}/balance`, method: "GET", signal },
    options,
  );
};

export const getGetBalanceQueryKey = (id?: string) => {
  return [`/api/users/${id}/balance`] as const;
};

export const getGetBalanceQueryOptions = <
  TData = Awaited<ReturnType<typeof getBalance>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getBalance>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetBalanceQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getBalance>>> = ({
    signal,
  }) => getBalance(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getBalance>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetBalanceQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBalance>>
>;
export type GetBalanceQueryError = ErrorType<void>;

/**
 * @summary Get user balance
 */

export function useGetBalance<
  TData = Awaited<ReturnType<typeof getBalance>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getBalance>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetBalanceQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Generate or regenerate access token for a user
 * @summary Generate access token
 */
export const generateToken = (
  id: string,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<unknown>(
    { url: `/api/users/${id}/token`, method: "POST", signal },
    options,
  );
};

export const getGenerateTokenMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof generateToken>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof generateToken>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["generateToken"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof generateToken>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return generateToken(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GenerateTokenMutationResult = NonNullable<
  Awaited<ReturnType<typeof generateToken>>
>;

export type GenerateTokenMutationError = ErrorType<void>;

/**
 * @summary Generate access token
 */
export const useGenerateToken = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof generateToken>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationResult<
  Awaited<ReturnType<typeof generateToken>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getGenerateTokenMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * Get current user info using Authorization header with Bearer token
 * @summary Get user by access token
 */
export const getUserByToken = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<unknown>(
    { url: `/api/users/me/token`, method: "GET", signal },
    options,
  );
};

export const getGetUserByTokenQueryKey = () => {
  return [`/api/users/me/token`] as const;
};

export const getGetUserByTokenQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserByToken>>,
  TError = ErrorType<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getUserByToken>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserByTokenQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserByToken>>> = ({
    signal,
  }) => getUserByToken(requestOptions, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserByToken>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetUserByTokenQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserByToken>>
>;
export type GetUserByTokenQueryError = ErrorType<void>;

/**
 * @summary Get user by access token
 */

export function useGetUserByToken<
  TData = Awaited<ReturnType<typeof getUserByToken>>,
  TError = ErrorType<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getUserByToken>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetUserByTokenQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get information about the current game state
 * @summary Get current game status
 */
export const getStatus = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<GameStatusResponseDto>(
    { url: `/api/game/status`, method: "GET", signal },
    options,
  );
};

export const getGetStatusQueryKey = () => {
  return [`/api/game/status`] as const;
};

export const getGetStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof getStatus>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getStatus>>, TError, TData>;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetStatusQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getStatus>>> = ({
    signal,
  }) => getStatus(requestOptions, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getStatus>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type GetStatusQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStatus>>
>;
export type GetStatusQueryError = ErrorType<unknown>;

/**
 * @summary Get current game status
 */

export function useGetStatus<
  TData = Awaited<ReturnType<typeof getStatus>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getStatus>>, TError, TData>;
  request?: SecondParameter<typeof customClient>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetStatusQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get detailed information about the currently running game
 * @summary Get current game details
 */
export const getCurrentGame = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<void>(
    { url: `/api/game/current`, method: "GET", signal },
    options,
  );
};

export const getGetCurrentGameQueryKey = () => {
  return [`/api/game/current`] as const;
};

export const getGetCurrentGameQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentGame>>,
  TError = ErrorType<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentGame>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCurrentGameQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentGame>>> = ({
    signal,
  }) => getCurrentGame(requestOptions, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentGame>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetCurrentGameQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCurrentGame>>
>;
export type GetCurrentGameQueryError = ErrorType<void>;

/**
 * @summary Get current game details
 */

export function useGetCurrentGame<
  TData = Awaited<ReturnType<typeof getCurrentGame>>,
  TError = ErrorType<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentGame>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetCurrentGameQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get the last N completed games
 * @summary Get game history
 */
export const getHistory = (
  params?: GetHistoryParams,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<GameHistoryResponseDto>(
    { url: `/api/game/history`, method: "GET", params, signal },
    options,
  );
};

export const getGetHistoryQueryKey = (params?: GetHistoryParams) => {
  return [`/api/game/history`, ...(params ? [params] : [])] as const;
};

export const getGetHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof getHistory>>,
  TError = ErrorType<unknown>,
>(
  params?: GetHistoryParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getHistory>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetHistoryQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getHistory>>> = ({
    signal,
  }) => getHistory(params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getHistory>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getHistory>>
>;
export type GetHistoryQueryError = ErrorType<unknown>;

/**
 * @summary Get game history
 */

export function useGetHistory<
  TData = Awaited<ReturnType<typeof getHistory>>,
  TError = ErrorType<unknown>,
>(
  params?: GetHistoryParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getHistory>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetHistoryQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get all completed games
 * @summary Get all game history
 */
export const getAllHistory = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<void>(
    { url: `/api/game/history/all`, method: "GET", signal },
    options,
  );
};

export const getGetAllHistoryQueryKey = () => {
  return [`/api/game/history/all`] as const;
};

export const getGetAllHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllHistory>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getAllHistory>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAllHistoryQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllHistory>>> = ({
    signal,
  }) => getAllHistory(requestOptions, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllHistory>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAllHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllHistory>>
>;
export type GetAllHistoryQueryError = ErrorType<unknown>;

/**
 * @summary Get all game history
 */

export function useGetAllHistory<
  TData = Awaited<ReturnType<typeof getAllHistory>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getAllHistory>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetAllHistoryQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get win/loss statistics for werewolf vs villager
 * @summary Get game statistics
 */
export const getStats = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<GameStatsResponseDto>(
    { url: `/api/game/stats`, method: "GET", signal },
    options,
  );
};

export const getGetStatsQueryKey = () => {
  return [`/api/game/stats`] as const;
};

export const getGetStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetStatsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getStats>>> = ({
    signal,
  }) => getStats(requestOptions, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type GetStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStats>>
>;
export type GetStatsQueryError = ErrorType<unknown>;

/**
 * @summary Get game statistics
 */

export function useGetStats<
  TData = Awaited<ReturnType<typeof getStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>;
  request?: SecondParameter<typeof customClient>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetStatsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get a preview of the upcoming game
 * @summary Get next game preview
 */
export const getNextPreview = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<void>(
    { url: `/api/game/next-preview`, method: "GET", signal },
    options,
  );
};

export const getGetNextPreviewQueryKey = () => {
  return [`/api/game/next-preview`] as const;
};

export const getGetNextPreviewQueryOptions = <
  TData = Awaited<ReturnType<typeof getNextPreview>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getNextPreview>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetNextPreviewQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getNextPreview>>> = ({
    signal,
  }) => getNextPreview(requestOptions, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getNextPreview>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetNextPreviewQueryResult = NonNullable<
  Awaited<ReturnType<typeof getNextPreview>>
>;
export type GetNextPreviewQueryError = ErrorType<unknown>;

/**
 * @summary Get next game preview
 */

export function useGetNextPreview<
  TData = Awaited<ReturnType<typeof getNextPreview>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getNextPreview>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetNextPreviewQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Immediately start the next game (admin only)
 * @summary [Admin] Force start next game
 */
export const forceNextGame = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<AdminActionResponseDto>(
    { url: `/api/game/admin/force-next`, method: "POST", signal },
    options,
  );
};

export const getForceNextGameMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof forceNextGame>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof forceNextGame>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["forceNextGame"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof forceNextGame>>,
    void
  > = () => {
    return forceNextGame(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ForceNextGameMutationResult = NonNullable<
  Awaited<ReturnType<typeof forceNextGame>>
>;

export type ForceNextGameMutationError = ErrorType<unknown>;

/**
 * @summary [Admin] Force start next game
 */
export const useForceNextGame = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof forceNextGame>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationResult<
  Awaited<ReturnType<typeof forceNextGame>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getForceNextGameMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * Pause the automatic game mode (admin only)
 * @summary [Admin] Pause auto mode
 */
export const pauseGame = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<AdminActionResponseDto>(
    { url: `/api/game/admin/pause`, method: "POST", signal },
    options,
  );
};

export const getPauseGameMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pauseGame>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof pauseGame>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["pauseGame"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof pauseGame>>,
    void
  > = () => {
    return pauseGame(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PauseGameMutationResult = NonNullable<
  Awaited<ReturnType<typeof pauseGame>>
>;

export type PauseGameMutationError = ErrorType<unknown>;

/**
 * @summary [Admin] Pause auto mode
 */
export const usePauseGame = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pauseGame>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationResult<
  Awaited<ReturnType<typeof pauseGame>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getPauseGameMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * Resume the automatic game mode (admin only)
 * @summary [Admin] Resume auto mode
 */
export const resumeGame = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<AdminActionResponseDto>(
    { url: `/api/game/admin/resume`, method: "POST", signal },
    options,
  );
};

export const getResumeGameMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof resumeGame>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof resumeGame>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["resumeGame"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof resumeGame>>,
    void
  > = () => {
    return resumeGame(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ResumeGameMutationResult = NonNullable<
  Awaited<ReturnType<typeof resumeGame>>
>;

export type ResumeGameMutationError = ErrorType<unknown>;

/**
 * @summary [Admin] Resume auto mode
 */
export const useResumeGame = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof resumeGame>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationResult<
  Awaited<ReturnType<typeof resumeGame>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getResumeGameMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * Place a bet on the current game
 * @summary Place a bet
 */
export const placeBet = (
  betRequestDto: BodyType<BetRequestDto>,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<BetResponseDto>(
    {
      url: `/api/game/bet`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: betRequestDto,
      signal,
    },
    options,
  );
};

export const getPlaceBetMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof placeBet>>,
    TError,
    { data: BodyType<BetRequestDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof placeBet>>,
  TError,
  { data: BodyType<BetRequestDto> },
  TContext
> => {
  const mutationKey = ["placeBet"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof placeBet>>,
    { data: BodyType<BetRequestDto> }
  > = (props) => {
    const { data } = props ?? {};

    return placeBet(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PlaceBetMutationResult = NonNullable<
  Awaited<ReturnType<typeof placeBet>>
>;
export type PlaceBetMutationBody = BodyType<BetRequestDto>;
export type PlaceBetMutationError = ErrorType<void>;

/**
 * @summary Place a bet
 */
export const usePlaceBet = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof placeBet>>,
    TError,
    { data: BodyType<BetRequestDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationResult<
  Awaited<ReturnType<typeof placeBet>>,
  TError,
  { data: BodyType<BetRequestDto> },
  TContext
> => {
  const mutationOptions = getPlaceBetMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * Place a bet on the current game using Bearer token authentication. No userId required in body.
 * @summary Place a bet with access token
 */
export const placeBetByToken = (
  betRequestDto: BodyType<BetRequestDto>,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<BetResponseDto>(
    {
      url: `/api/game/bet/token`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: betRequestDto,
      signal,
    },
    options,
  );
};

export const getPlaceBetByTokenMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof placeBetByToken>>,
    TError,
    { data: BodyType<BetRequestDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof placeBetByToken>>,
  TError,
  { data: BodyType<BetRequestDto> },
  TContext
> => {
  const mutationKey = ["placeBetByToken"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof placeBetByToken>>,
    { data: BodyType<BetRequestDto> }
  > = (props) => {
    const { data } = props ?? {};

    return placeBetByToken(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PlaceBetByTokenMutationResult = NonNullable<
  Awaited<ReturnType<typeof placeBetByToken>>
>;
export type PlaceBetByTokenMutationBody = BodyType<BetRequestDto>;
export type PlaceBetByTokenMutationError = ErrorType<void>;

/**
 * @summary Place a bet with access token
 */
export const usePlaceBetByToken = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof placeBetByToken>>,
    TError,
    { data: BodyType<BetRequestDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationResult<
  Awaited<ReturnType<typeof placeBetByToken>>,
  TError,
  { data: BodyType<BetRequestDto> },
  TContext
> => {
  const mutationOptions = getPlaceBetByTokenMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * Get all bets placed by a specific user
 * @summary Get user's bets
 */
export const getUserBets = (
  userId: string,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<void>(
    { url: `/api/game/bets/${userId}`, method: "GET", signal },
    options,
  );
};

export const getGetUserBetsQueryKey = (userId?: string) => {
  return [`/api/game/bets/${userId}`] as const;
};

export const getGetUserBetsQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserBets>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getUserBets>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserBetsQueryKey(userId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserBets>>> = ({
    signal,
  }) => getUserBets(userId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!userId,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserBets>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetUserBetsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserBets>>
>;
export type GetUserBetsQueryError = ErrorType<unknown>;

/**
 * @summary Get user's bets
 */

export function useGetUserBets<
  TData = Awaited<ReturnType<typeof getUserBets>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getUserBets>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetUserBetsQueryOptions(userId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get all pending bets for a specific user
 * @summary Get user's pending bets
 */
export const getUserPendingBets = (
  userId: string,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<void>(
    { url: `/api/game/bets/${userId}/pending`, method: "GET", signal },
    options,
  );
};

export const getGetUserPendingBetsQueryKey = (userId?: string) => {
  return [`/api/game/bets/${userId}/pending`] as const;
};

export const getGetUserPendingBetsQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserPendingBets>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getUserPendingBets>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetUserPendingBetsQueryKey(userId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUserPendingBets>>
  > = ({ signal }) => getUserPendingBets(userId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!userId,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserPendingBets>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetUserPendingBetsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserPendingBets>>
>;
export type GetUserPendingBetsQueryError = ErrorType<unknown>;

/**
 * @summary Get user's pending bets
 */

export function useGetUserPendingBets<
  TData = Awaited<ReturnType<typeof getUserPendingBets>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getUserPendingBets>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customClient>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetUserPendingBetsQueryOptions(userId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get list of players in the current game for betting reference
 * @summary Get current game players
 */
export const getCurrentPlayers = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<void>(
    { url: `/api/game/current/players`, method: "GET", signal },
    options,
  );
};

export const getGetCurrentPlayersQueryKey = () => {
  return [`/api/game/current/players`] as const;
};

export const getGetCurrentPlayersQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentPlayers>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentPlayers>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCurrentPlayersQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCurrentPlayers>>
  > = ({ signal }) => getCurrentPlayers(requestOptions, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentPlayers>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetCurrentPlayersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCurrentPlayers>>
>;
export type GetCurrentPlayersQueryError = ErrorType<unknown>;

/**
 * @summary Get current game players
 */

export function useGetCurrentPlayers<
  TData = Awaited<ReturnType<typeof getCurrentPlayers>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentPlayers>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetCurrentPlayersQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get detailed game progress including all events from the start of the current game to now
 * @summary Get current game progress
 */
export const getGameProgress = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<GameProgressResponseDto>(
    { url: `/api/game/progress`, method: "GET", signal },
    options,
  );
};

export const getGetGameProgressQueryKey = () => {
  return [`/api/game/progress`] as const;
};

export const getGetGameProgressQueryOptions = <
  TData = Awaited<ReturnType<typeof getGameProgress>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getGameProgress>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetGameProgressQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getGameProgress>>> = ({
    signal,
  }) => getGameProgress(requestOptions, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getGameProgress>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetGameProgressQueryResult = NonNullable<
  Awaited<ReturnType<typeof getGameProgress>>
>;
export type GetGameProgressQueryError = ErrorType<unknown>;

/**
 * @summary Get current game progress
 */

export function useGetGameProgress<
  TData = Awaited<ReturnType<typeof getGameProgress>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getGameProgress>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customClient>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetGameProgressQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getSkills = (
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal,
) => {
  return customClient<void>(
    { url: `/api/game/skills`, method: "GET", signal },
    options,
  );
};

export const getGetSkillsQueryKey = () => {
  return [`/api/game/skills`] as const;
};

export const getGetSkillsQueryOptions = <
  TData = Awaited<ReturnType<typeof getSkills>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getSkills>>, TError, TData>;
  request?: SecondParameter<typeof customClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSkillsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSkills>>> = ({
    signal,
  }) => getSkills(requestOptions, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getSkills>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type GetSkillsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSkills>>
>;
export type GetSkillsQueryError = ErrorType<unknown>;

export function useGetSkills<
  TData = Awaited<ReturnType<typeof getSkills>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getSkills>>, TError, TData>;
  request?: SecondParameter<typeof customClient>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetSkillsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
