/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Adoption Level Enum - for categorizing adoption and activity level
 */
export type AdoptionLevel = typeof AdoptionLevel[keyof typeof AdoptionLevel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdoptionLevel = {
  'Đáng_chú_ý,_adoption_cao_và_hoạt_động_sôi_động': 'Đáng chú ý, adoption cao và hoạt động sôi động',
  'Bình_thường,_adoption_và_hoạt_động_không_nổi_bật': 'Bình thường, adoption và hoạt động không nổi bật',
} as const;
