/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */
import type { MarketRisk } from './marketRisk';

export interface AggregateMarketRiskDto {
  market_risk: MarketRisk;
  risk_score: number;
  max_score: number;
  min_score: number;
}
