/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

export type ApisPart08NarrativeTopProjectsSupportedSector = typeof ApisPart08NarrativeTopProjectsSupportedSector[keyof typeof ApisPart08NarrativeTopProjectsSupportedSector];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApisPart08NarrativeTopProjectsSupportedSector = {
  exchange: 'exchange',
  lending: 'lending',
  'stablecoin-issuers': 'stablecoin-issuers',
  'blockchains-l2': 'blockchains-l2',
  'blockchains-l1': 'blockchains-l1',
  'liquid-staking': 'liquid-staking',
  nft: 'nft',
  derivatives: 'derivatives',
  RWA: 'RWA',
  oracle: 'oracle',
} as const;
