/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 🐺 Werewolf Betting Game API
 * API for Werewolf Betting Game with auto-play mode. WebSocket namespace: /game
 * OpenAPI spec version: 1.0.0
 */
import type { BetRequestDtoBetType } from './betRequestDtoBetType';
import type { BetRequestDtoPredictedWinner } from './betRequestDtoPredictedWinner';

export interface BetRequestDto {
  /** User ID placing the bet */
  userId: string;
  /** Game ID to place bet on */
  gameId: string;
  /** Type of bet */
  betType: BetRequestDtoBetType;
  /**
   * Amount to bet
   * @minimum 1
   */
  amount: number;
  /** Target player ID (required for WEREWOLF and NEXT_DEATH bets) */
  targetId?: string;
  /** Predicted winner team (required for WINNER bets) */
  predictedWinner?: BetRequestDtoPredictedWinner;
}
