/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 🐺 Werewolf Betting Game API
 * API for Werewolf Betting Game with auto-play mode. WebSocket namespace: /game
 * OpenAPI spec version: 1.0.0
 */

/**
 * Predicted winner team (required for WINNER bets)
 */
export type BetRequestDtoPredictedWinner = typeof BetRequestDtoPredictedWinner[keyof typeof BetRequestDtoPredictedWinner];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BetRequestDtoPredictedWinner = {
  werewolf: 'werewolf',
  villager: 'villager',
} as const;
