/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Blockchain Liquidity Enum
 */
export type BlockchainLiquidity = typeof BlockchainLiquidity[keyof typeof BlockchainLiquidity];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BlockchainLiquidity = {
  'Liquidity_Increasing_(Thanh_khoản_tốt_và_tăng)': 'Liquidity Increasing (Thanh khoản tốt và tăng)',
  'Liquidity_Decreasing_(Thanh_khoản_yếu_hoặc_giảm)': 'Liquidity Decreasing (Thanh khoản yếu hoặc giảm)',
  'Liquidity_Neutral_(Thanh_khoản_ổn_định)': 'Liquidity Neutral (Thanh khoản ổn định)',
} as const;
