/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */
import type { BtcVolatility } from './btcVolatility';

export interface BtcVolatilityDto {
  btc_volatility: BtcVolatility;
  atr_current: number;
  atr_min: number;
  atr_max: number;
}
