/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * BTC Volatility Enum - for detect_btc_volatility function
 */
export type BtcVolatility = typeof BtcVolatility[keyof typeof BtcVolatility];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BtcVolatility = {
  'High_Volatility_/_BTC_đang_giao_động_mạnh': 'High Volatility / BTC đang giao động mạnh',
  'Low_Volatility_/_BTC_sideway_hoặc_biến_động_yếu': 'Low Volatility / BTC sideway hoặc biến động yếu',
  'Medium_Volatility_/_Biến_động_vừa_phải': 'Medium Volatility / Biến động vừa phải',
} as const;
