/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Core Activity Growth Enum - for categorizing core activity growth
 */
export type CoreActivityGrowth = typeof CoreActivityGrowth[keyof typeof CoreActivityGrowth];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CoreActivityGrowth = {
  Core_Activity_tăng_trưởng_mạnh: 'Core Activity tăng trưởng mạnh',
  Core_Activity_tăng_trưởng_vừa_phải: 'Core Activity tăng trưởng vừa phải',
  Core_Activity_tăng_trưởng_nhẹ: 'Core Activity tăng trưởng nhẹ',
} as const;
