/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Core Activity Status Enum - for categorizing core activity performance
 */
export type CoreActivityStatus = typeof CoreActivityStatus[keyof typeof CoreActivityStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CoreActivityStatus = {
  Core_hoạt_động_chính_tăng_trưởng_tốt: 'Core hoạt động chính tăng trưởng tốt',
  Core_hoạt_động_chính_tăng_trưởng_không_tốt: 'Core hoạt động chính tăng trưởng không tốt',
} as const;
