/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Cost of Capital Score Enum
 */
export type CostOfCapitalScore = typeof CostOfCapitalScore[keyof typeof CostOfCapitalScore];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CostOfCapitalScore = {
  High: 'High',
  Medium: 'Medium',
  Low: 'Low',
} as const;
