/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 🐺 Werewolf Betting Game API
 * API for Werewolf Betting Game with auto-play mode. WebSocket namespace: /game
 * OpenAPI spec version: 1.0.0
 */

export interface CreateUserDto {
  /** User ID (optional, will be auto-generated if not provided) */
  id?: string;
  /** Username of the user */
  username: string;
  /**
   * Initial balance for the user
   * @minimum 0
   */
  balance?: number;
}
