/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Viral Bot API
 * OpenAPI spec version: 0.0.12
 */

export interface CreateMemeParamsResponse {
  readonly invoker: string;
  readonly tokenId: string;
  readonly feeFree: boolean;
  readonly tokenOffset: string;
  readonly quoteOffset: string;
  readonly expiredBlockNumber: string;
  readonly tokenAddress: string;
}
