/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Crypto Global Market Risk Score Enum
 */
export type CryptoGlobalMarketRiskScore = typeof CryptoGlobalMarketRiskScore[keyof typeof CryptoGlobalMarketRiskScore];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CryptoGlobalMarketRiskScore = {
  Risk_on: 'Risk on',
  Neutral: 'Neutral',
  Risk_off: 'Risk off',
  Not_sure_yet: 'Not sure yet',
} as const;
