/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Crypto Market State Enum
 */
export type CryptoMarketState = typeof CryptoMarketState[keyof typeof CryptoMarketState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CryptoMarketState = {
  'Thị_trường_mạnh:_dòng_tiền_vào,_tâm_lý_tích_cực,_on-chain_activity_tốt': 'Thị trường mạnh: dòng tiền vào, tâm lý tích cực, on-chain activity tốt',
  'Thị_trường_yếu:_dòng_tiền_ra,_tâm_lý_tiêu_cực,_rủi_ro_cao': 'Thị trường yếu: dòng tiền ra, tâm lý tiêu cực, rủi ro cao',
  'Thị_trường_trung_lập:_ổn_định,_sideway,_cần_quan_sát_thêm': 'Thị trường trung lập: ổn định, sideway, cần quan sát thêm',
} as const;
