/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */
import type { CryptoGlobalMarketRiskScore } from './cryptoGlobalMarketRiskScore';

export interface CryptoGlobalMarketRiskDTO {
  crypto_risk_score: number;
  max_score: number;
  min_score: number;
  crypto_risk_level: CryptoGlobalMarketRiskScore;
}
