/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */
import type { MarketState } from './marketState';

export interface CryptoMarketStateDto {
  total_score: number;
  market_state: MarketState;
  min_score: number;
  max_score: number;
}
