/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

export interface CurrentLiquidationRatioDto {
  datetime: string;
  current_ratio: number;
  max_ratio: number;
  min_ratio: number;
}
