/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * DTO for DeFi ecosystem engagement metrics

Fields:
    protocol: Protocol name/symbol
    engagement_score: User engagement score for the protocol
 */
export interface DefiEcoEngagementDto {
  protocol: string;
  engagement_score: number;
}
