/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Enum representing the scale of DeFi ecosystem based on total TVL
 */
export type DeFiEcosystemScale = typeof DeFiEcosystemScale[keyof typeof DeFiEcosystemScale];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeFiEcosystemScale = {
  Lớn: 'Lớn',
  Trung_bình: 'Trung bình',
  Nhỏ: 'Nhỏ',
} as const;
