/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */
import type { DeFiEcosystemScale } from './deFiEcosystemScale';

/**
 * DTO for DeFi ecosystem scale assessment

Fields:
    defi_ecosystem_scale: The scale classification (Large, Medium, Small)
    total_tvl: Total value locked across all protocols
 */
export interface DefiEcoScaleDto {
  scale: DeFiEcosystemScale;
}
