/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * DEX TVL Share Enum - for categorizing DEX TVL share
 */
export type DexTvlShare = typeof DexTvlShare[keyof typeof DexTvlShare];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DexTvlShare = {
  Chiếm_lĩnh_DEX: 'Chiếm lĩnh DEX',
  Đáng_quan_tâm: 'Đáng quan tâm',
  Nhỏ: 'Nhỏ',
} as const;
