/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Viral Bot API
 * OpenAPI spec version: 0.0.12
 */

export type EarningAmountResponseStatus = typeof EarningAmountResponseStatus[keyof typeof EarningAmountResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EarningAmountResponseStatus = {
  active: 'active',
  hidden: 'hidden',
  ended: 'ended',
  completed: 'completed',
} as const;
