/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Viral Bot API
 * OpenAPI spec version: 0.0.12
 */
import type { EarningAmountResponseStatus } from './earningAmountResponseStatus';

export interface EarningAmountResponse {
  readonly id: number;
  readonly created_at: string;
  readonly updated_at: string;
  readonly status: EarningAmountResponseStatus;
  readonly tokenAddress: string;
  readonly quoteAddress: string;
  readonly creator: string;
  readonly name: string;
  readonly symbol: string;
  readonly decimals: string;
  readonly memeContentId: number;
  readonly tokenOffset: string;
  readonly quoteOffset: string;
  readonly totalSupply: string;
  readonly saleAmount: string;
  readonly virtualQuoteReserve: string;
  readonly virtualTokenReserve: string;
  readonly pairAddress: string;
  readonly createdTime: number;
  readonly graduatedTime: number;
  readonly volume24hs: string;
  readonly volume48hs: string;
  readonly currentPriceByUsd: string;
  readonly price24hChange: string;
  readonly volumeBuyByQuote: string;
  readonly kingOfTheHillTime: number;
  readonly isUserLike: boolean;
  readonly listProgress: string;
  readonly kingOfTheHillProgress: string;
  readonly marketCap: string;
  readonly totalEarningAmount: string;
}
