/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

export type ETFAsset = typeof ETFAsset[keyof typeof ETFAsset];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ETFAsset = {
  BTC: 'BTC',
  ETH: 'ETH',
} as const;
