/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */
import type { EtfBias } from './etfBias';

export interface EtfBiasDto {
  etf_bias: EtfBias;
  btc_etf_flow: number;
  eth_etf_flow: number;
  max_score: number;
  min_score: number;
}
