/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * ETF Bias Enum
 */
export type EtfBias = typeof EtfBias[keyof typeof EtfBias];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EtfBias = {
  Dòng_tiền_bias_BTC: 'Dòng tiền bias BTC',
  Dòng_tiền_bias_ETH: 'Dòng tiền bias ETH',
  Dòng_tiền_Mixed: 'Dòng tiền Mixed',
} as const;
