/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */
import type { DexTvlShare } from './dexTvlShare';
import type { OverallGrowth } from './overallGrowth';

/**
 * DTO for Exchange (DEX) project metrics
 */
export interface ExchangeProjectDto {
  protocol: string;
  latest_tvl: number;
  tvl_share: number;
  percentage_change_tvl: number;
  percentage_change_trading_volume: number;
  percentage_change_active_users: number;
  percentage_change_fees: number;
  dex_tvl_share_class: DexTvlShare;
  overall_growth_class: OverallGrowth;
}
