/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

export type ExchangeNetflowAsset = typeof ExchangeNetflowAsset[keyof typeof ExchangeNetflowAsset];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExchangeNetflowAsset = {
  BTC: 'BTC',
  ETH: 'ETH',
  USD: 'USD',
} as const;
