/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Flow Spot vs Futures Enum - for detect_flow_spot_vs_futures function
 */
export type FlowSpotVsFutures = typeof FlowSpotVsFutures[keyof typeof FlowSpotVsFutures];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FlowSpotVsFutures = {
  Dòng_tiền_chạy_vào_Spot: 'Dòng tiền chạy vào Spot',
  Dòng_tiền_chạy_vào_Futures: 'Dòng tiền chạy vào Futures',
  Trung_lập: 'Trung lập',
} as const;
