/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */
import type { FlowCexVsDex } from './flowCexVsDex';

export interface FlowCexVsDexDto {
  cex_score: number;
  dex_score: number;
  result: FlowCexVsDex;
}
