/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Flow CEX vs DEX Enum - for detect_flow_cex_vs_dex function
 */
export type FlowCexVsDex = typeof FlowCexVsDex[keyof typeof FlowCexVsDex];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FlowCexVsDex = {
  Dòng_tiền_chạy_vào_CEX: 'Dòng tiền chạy vào CEX',
  Dòng_tiền_chạy_vào_DEX: 'Dòng tiền chạy vào DEX',
  Trung_lập: 'Trung lập',
} as const;
