/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Flow Direction Enum - for detect_flow_direction function
 */
export type FlowDirectionEnum = typeof FlowDirectionEnum[keyof typeof FlowDirectionEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FlowDirectionEnum = {
  BTC: 'BTC',
  ETH: 'ETH',
  Altcoins: 'Altcoins',
  Mixed: 'Mixed',
  Neutral: 'Neutral',
} as const;
