/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */
import type { FundamentalTrend } from './fundamentalTrend';

export interface FundamentalTrendDto {
  fundamental_trend: FundamentalTrend;
  fundamental_score: number;
  max_score: number;
  min_score: number;
}
