/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Fundamental Trend Enum
 */
export type FundamentalTrend = typeof FundamentalTrend[keyof typeof FundamentalTrend];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FundamentalTrend = {
  'Trend_mạnh/bền_(adoption_tốt)': 'Trend mạnh/bền (adoption tốt)',
  'Trend_ngắn_hạn_(volume_tăng_nhưng_adoption_chưa_bền)': 'Trend ngắn hạn (volume tăng nhưng adoption chưa bền)',
} as const;
