/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 🐺 Werewolf Betting Game API
 * API for Werewolf Betting Game with auto-play mode. WebSocket namespace: /game
 * OpenAPI spec version: 1.0.0
 */
import type { GameProgressResponseDtoCurrentPhase } from './gameProgressResponseDtoCurrentPhase';
import type { GameEventDto } from './gameEventDto';
import type { GameMessageDto } from './gameMessageDto';
import type { PlayersProgressDto } from './playersProgressDto';
import type { GameStatsDto } from './gameStatsDto';

export interface GameProgressResponseDto {
  gameId: string;
  isRunning: boolean;
  startedAt?: string;
  currentRound: number;
  totalRounds: number;
  currentPhase?: GameProgressResponseDtoCurrentPhase;
  events: GameEventDto[];
  messages: GameMessageDto[];
  players: PlayersProgressDto;
  stats: GameStatsDto;
}
