/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 🐺 Werewolf Betting Game API
 * API for Werewolf Betting Game with auto-play mode. WebSocket namespace: /game
 * OpenAPI spec version: 1.0.0
 */

export interface GameStatsDto {
  /** Total deaths in game */
  totalDeaths: number;
  /** Number of day eliminations */
  eliminations: number;
  /** Number of night deaths */
  nightDeaths: number;
}
