/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 🐺 Werewolf Betting Game API
 * API for Werewolf Betting Game with auto-play mode. WebSocket namespace: /game
 * OpenAPI spec version: 1.0.0
 */
import type { GameStatsResponseDtoWinRate } from './gameStatsResponseDtoWinRate';

export interface GameStatsResponseDto {
  totalGames: number;
  werewolfWins: number;
  villagerWins: number;
  winRate: GameStatsResponseDtoWinRate;
}
