/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 🐺 Werewolf Betting Game API
 * API for Werewolf Betting Game with auto-play mode. WebSocket namespace: /game
 * OpenAPI spec version: 1.0.0
 */

export type GameResultDtoWinner = typeof GameResultDtoWinner[keyof typeof GameResultDtoWinner];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GameResultDtoWinner = {
  werewolf: 'werewolf',
  villager: 'villager',
} as const;
