/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 🐺 Werewolf Betting Game API
 * API for Werewolf Betting Game with auto-play mode. WebSocket namespace: /game
 * OpenAPI spec version: 1.0.0
 */
import type { GameEventDtoType } from './gameEventDtoType';
import type { GameEventDtoPhase } from './gameEventDtoPhase';
import type { GameEventDtoData } from './gameEventDtoData';

export interface GameEventDto {
  type: GameEventDtoType;
  gameId: string;
  roundNumber?: number;
  phase?: GameEventDtoPhase;
  data?: GameEventDtoData;
  timestamp: number;
}
