/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 🐺 Werewolf Betting Game API
 * API for Werewolf Betting Game with auto-play mode. WebSocket namespace: /game
 * OpenAPI spec version: 1.0.0
 */

export type GameEventDtoType = typeof GameEventDtoType[keyof typeof GameEventDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GameEventDtoType = {
  GAME_START: 'GAME_START',
  NIGHT_START: 'NIGHT_START',
  NIGHT_ACTION: 'NIGHT_ACTION',
  NIGHT_DEATH: 'NIGHT_DEATH',
  DAY_START: 'DAY_START',
  DAY_MESSAGE: 'DAY_MESSAGE',
  DAY_VOTE: 'DAY_VOTE',
  DAY_ELIMINATION: 'DAY_ELIMINATION',
  GAME_END: 'GAME_END',
} as const;
