/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */
import type { NarrativeMoneyCoinDto } from './narrativeMoneyCoinDto';

export type GetDefiFundamentalNarrativeMoneyCoinScoreDefiFundamentalNarrativeMoneyCoinGet200 = {[key: string]: NarrativeMoneyCoinDto};
