/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */
import type { GlobalRisk } from './globalRisk';

export interface GlobalRiskDto {
  global_risk: GlobalRisk;
  vix_value: number;
  max_score: number;
  min_score: number;
}
