/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */
import type { LiquidityScore } from './liquidityScore';

export interface GlobalLiquidityDTO {
  liquidity_score: number;
  max_score: number;
  min_score: number;
  liquidity_level: LiquidityScore;
}
