/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */
import type { CostOfCapitalScore } from './costOfCapitalScore';

export interface GlobalCostOfCapitalDTO {
  cost_of_capital_score: number;
  max_score: number;
  min_score: number;
  cost_of_capital_level: CostOfCapitalScore;
}
