/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Global Risk Enum - for detect_global_risk function
 */
export type GlobalRisk = typeof GlobalRisk[keyof typeof GlobalRisk];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GlobalRisk = {
  'High_Risk_/_Khả_năng_cú_quét_mạnh_cao': 'High Risk / Khả năng cú quét mạnh cao',
  'Medium_Risk_/_Rủi_ro_vừa_phải': 'Medium Risk / Rủi ro vừa phải',
  'Low_Risk_/_Thị_trường_bình_ổn': 'Low Risk / Thị trường bình ổn',
} as const;
