/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */
import type { MoneyFlowScore } from './moneyFlowScore';

export interface GlobalMoneyFlowDTO {
  money_flow_score: number;
  max_score: number;
  min_score: number;
  money_flow_level: MoneyFlowScore;
}
