/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Growth Trend Enum - for categorizing growth/change percentage
 */
export type GrowthTrend = typeof GrowthTrend[keyof typeof GrowthTrend];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GrowthTrend = {
  Tăng_trưởng_mạnh: 'Tăng trưởng mạnh',
  Tăng_trưởng_vừa_phải: 'Tăng trưởng vừa phải',
  Tăng_trưởng_nhẹ: 'Tăng trưởng nhẹ',
} as const;
