/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */
import type { SimpleGrowth } from './simpleGrowth';

/**
 * DTO for L1 project metrics
 */
export interface L1ProjectDto {
  protocol: string;
  latest_active_users: number;
  latest_fees: number;
  latest_tps: number;
  percentage_change_active_users: number;
  percentage_change_fees: number;
  percentage_change_tps: number;
  growth_class: SimpleGrowth;
}
