/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */
import type { L2Share } from './l2Share';
import type { SimpleGrowth } from './simpleGrowth';
import type { CoreActivityStatus } from './coreActivityStatus';

/**
 * DTO for L2 project metrics
 */
export interface L2ProjectDto {
  protocol: string;
  latest_bridge_deposits: number;
  bridge_deposit_share: number;
  percentage_change_bridge_deposits: number;
  percentage_change_active_users: number;
  percentage_change_fees: number;
  l2_share_class: L2Share;
  growth_class: SimpleGrowth;
  core_activity_class: CoreActivityStatus;
}
