/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * L2 Share Enum - for categorizing L2 bridge deposit share
 */
export type L2Share = typeof L2Share[keyof typeof L2Share];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const L2Share = {
  Chiếm_lĩnh_L2: 'Chiếm lĩnh L2',
  Đáng_quan_tâm: 'Đáng quan tâm',
  Nhỏ: 'Nhỏ',
} as const;
