/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */
import type { LendingTvlShare } from './lendingTvlShare';
import type { OverallGrowth } from './overallGrowth';
import type { LoanActivity } from './loanActivity';

/**
 * DTO for Lending project metrics
 */
export interface LendingProjectDto {
  protocol: string;
  latest_tvl: number;
  tvl_share: number;
  percentage_change_tvl: number;
  percentage_change_active_users: number;
  percentage_change_fees: number;
  percentage_change_active_loans: number;
  lending_tvl_share_class: LendingTvlShare;
  overall_growth_class: OverallGrowth;
  loan_activity_class: LoanActivity;
}
