/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Lending TVL Share Enum - for categorizing Lending TVL share
 */
export type LendingTvlShare = typeof LendingTvlShare[keyof typeof LendingTvlShare];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LendingTvlShare = {
  Chiếm_lĩnh_Lending: 'Chiếm lĩnh Lending',
  Đáng_quan_tâm: 'Đáng quan tâm',
  Nhỏ: 'Nhỏ',
} as const;
