/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

export interface LiquidationDataDto {
  datetime: string;
  value_long: number;
  value_short: number;
}
