/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Liquid Staking Share Enum - for categorizing liquid staking share
 */
export type LiquidStakingShare = typeof LiquidStakingShare[keyof typeof LiquidStakingShare];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LiquidStakingShare = {
  Chiếm_lĩnh_Liquid_Staking: 'Chiếm lĩnh Liquid Staking',
  Vừa_phải: 'Vừa phải',
  Nhỏ: 'Nhỏ',
} as const;
