/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */
import type { LiquidStakingShare } from './liquidStakingShare';
import type { CoreActivityGrowth } from './coreActivityGrowth';
import type { NetworkEconomyStrength } from './networkEconomyStrength';

/**
 * DTO for Liquid Staking project metrics
 */
export interface LiquidStakingProjectDto {
  protocol: string;
  latest_assets_staked: number;
  latest_fees: number;
  assets_stake_share: number;
  fees_share: number;
  percentage_change_assets_staked: number;
  percentage_change_fees: number;
  staking_share_class: LiquidStakingShare;
  core_activity_class: CoreActivityGrowth;
  network_economy_class: NetworkEconomyStrength;
}
