/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Loan Activity Enum - for categorizing lending loan activity
 */
export type LoanActivity = typeof LoanActivity[keyof typeof LoanActivity];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoanActivity = {
  Hoạt_động_vay_mạnh_mẽ: 'Hoạt động vay mạnh mẽ',
  Hoạt_động_vay_không_mạnh_mẽ: 'Hoạt động vay không mạnh mẽ',
} as const;
