/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Market State Enum - for aggregate_crypto_market_state function
 */
export type MarketState = typeof MarketState[keyof typeof MarketState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MarketState = {
  'Bullish_/_Thị_trường_mạnh': 'Bullish / Thị trường mạnh',
  'Bearish_/_Thị_trường_yếu': 'Bearish / Thị trường yếu',
  'Neutral_/_Thị_trường_ổn_định': 'Neutral / Thị trường ổn định',
} as const;
