/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Market Risk Enum - for aggregate_market_risk function
 */
export type MarketRisk = typeof MarketRisk[keyof typeof MarketRisk];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MarketRisk = {
  'High_Volatility_&_High_Risk_/_Thị_trường_biến_động_mạnh,_rủi_ro_cao': 'High Volatility & High Risk / Thị trường biến động mạnh, rủi ro cao',
  'Medium_Volatility_&_Risk_/_Thị_trường_biến_động_vừa_phải': 'Medium Volatility & Risk / Thị trường biến động vừa phải',
  'Low_Volatility_&_Low_Risk_/_Thị_trường_ổn_định,_biến_động_thấp': 'Low Volatility & Low Risk / Thị trường ổn định, biến động thấp',
} as const;
