/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Market Psychology Enum
 */
export type MarketPsychology = typeof MarketPsychology[keyof typeof MarketPsychology];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MarketPsychology = {
  Extreme_Fear: 'Extreme Fear',
  Fear: 'Fear',
  Neutral: 'Neutral',
  Greed: 'Greed',
  Extreme_Greed: 'Extreme Greed',
} as const;
