/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */
import type { MarketVolatilityLevel } from './marketVolatilityLevel';
import type { MarketPressure } from './marketPressure';

export interface MarketVolatilityLongShortDto {
  volatility: MarketVolatilityLevel;
  pressure: MarketPressure;
}
