/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Market Risk Score Enum
 */
export type MarketRiskScore = typeof MarketRiskScore[keyof typeof MarketRiskScore];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MarketRiskScore = {
  Risk_on: 'Risk on',
  Risk_off: 'Risk off',
  Neutral: 'Neutral',
} as const;
