/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Market Volatility Level Enum - for detect_market_volatility_long_short function
 */
export type MarketVolatilityLevel = typeof MarketVolatilityLevel[keyof typeof MarketVolatilityLevel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MarketVolatilityLevel = {
  High_Volatility: 'High Volatility',
  Medium_Volatility: 'Medium Volatility',
  Low_Volatility: 'Low Volatility',
} as const;
