/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Market Sentiment Onchain Enum
 */
export type MarketSentimentOnchain = typeof MarketSentimentOnchain[keyof typeof MarketSentimentOnchain];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MarketSentimentOnchain = {
  'Niềm_tin_cao_/_FOMO_tăng': 'Niềm tin cao / FOMO tăng',
  'Niềm_tin_thấp_/_Thị_trường_sợ_hãi': 'Niềm tin thấp / Thị trường sợ hãi',
  'Niềm_tin_trung_lập_/_FOMO_không_rõ': 'Niềm tin trung lập / FOMO không rõ',
} as const;
