/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */
import type { MarketSentiment } from './marketSentiment';

export interface MarketSentimentDto {
  market_sentiment: MarketSentiment;
}
