/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Market Pressure Enum - for detect_market_volatility_long_short function
 */
export type MarketPressure = typeof MarketPressure[keyof typeof MarketPressure];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MarketPressure = {
  Longs_under_pressure: 'Longs under pressure',
  Shorts_under_pressure: 'Shorts under pressure',
  Balanced: 'Balanced',
} as const;
