/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Market Sentiment Enum - for detect_market_sentiment function
 */
export type MarketSentiment = typeof MarketSentiment[keyof typeof MarketSentiment];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MarketSentiment = {
  'Bullish_/_Tâm_lý_thị_trường_tích_cực': 'Bullish / Tâm lý thị trường tích cực',
  'Bearish_/_Tâm_lý_thị_trường_tiêu_cực': 'Bearish / Tâm lý thị trường tiêu cực',
  'Neutral_/_Tâm_lý_trung_lập': 'Neutral / Tâm lý trung lập',
} as const;
