/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Viral Bot API
 * OpenAPI spec version: 0.0.12
 */
import type { MemeContentResponseStatus } from './memeContentResponseStatus';
import type { MediaResponse } from './mediaResponse';
import type { MemeContentInteractionResponse } from './memeContentInteractionResponse';

export interface MemeContentResponse {
  readonly id: number;
  readonly created_at: string;
  readonly updated_at: string;
  readonly status: MemeContentResponseStatus;
  readonly createdTime: number;
  readonly invokerXUserId: string;
  readonly subPostId: string;
  readonly subBodyPost: string;
  readonly mainBodyPost: string;
  readonly mainCreatedTime: number;
  readonly mainPostId: string;
  readonly mainXUserId: string;
  readonly medias: readonly MediaResponse[];
  readonly tokenAddress: string;
  readonly name: string;
  readonly symbol: string;
  readonly interactions: MemeContentInteractionResponse;
}
