/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Viral Bot API
 * OpenAPI spec version: 0.0.12
 */

export type MemeControllerQueryPaginationSortBy = typeof MemeControllerQueryPaginationSortBy[keyof typeof MemeControllerQueryPaginationSortBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemeControllerQueryPaginationSortBy = {
  createdTime: 'createdTime',
  volume24hs: 'volume24hs',
  currentPriceByUsd: 'currentPriceByUsd',
  totalInteractions: 'totalInteractions',
} as const;
