/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Viral Bot API
 * OpenAPI spec version: 0.0.12
 */

export type MemeContentResponseStatus = typeof MemeContentResponseStatus[keyof typeof MemeContentResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemeContentResponseStatus = {
  pending: 'pending',
  active: 'active',
  used: 'used',
  rejected: 'rejected',
} as const;
