/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Viral Bot API
 * OpenAPI spec version: 0.0.12
 */

export type MemeControllerQueryPaginationSortOrder = typeof MemeControllerQueryPaginationSortOrder[keyof typeof MemeControllerQueryPaginationSortOrder];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemeControllerQueryPaginationSortOrder = {
  DESC: 'DESC',
  ASC: 'ASC',
} as const;
