/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Viral Bot API
 * OpenAPI spec version: 0.0.12
 */
import type { MemeContentDetailResponse } from './memeContentDetailResponse';

export interface MemeContentsPaginationResponse {
  readonly total: number;
  readonly page: number;
  readonly pageSize: number;
  readonly data: readonly MemeContentDetailResponse[];
}
