/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Viral Bot API
 * OpenAPI spec version: 0.0.12
 */

export type MemeControllerQueryPaginationFilter = typeof MemeControllerQueryPaginationFilter[keyof typeof MemeControllerQueryPaginationFilter];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemeControllerQueryPaginationFilter = {
  all: 'all',
  bonding: 'bonding',
  new: 'new',
  finalizing: 'finalizing',
  end: 'end',
} as const;
