/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Money Flow Score Enum
 */
export type MoneyFlowScore = typeof MoneyFlowScore[keyof typeof MoneyFlowScore];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MoneyFlowScore = {
  Fast: 'Fast',
  Medium: 'Medium',
  Slow: 'Slow',
} as const;
