/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Money Flow Enum - for detect_money_flow function
 */
export type MoneyFlow = typeof MoneyFlow[keyof typeof MoneyFlow];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MoneyFlow = {
  'Dòng_tiền_vào_(Inflow)': 'Dòng tiền vào (Inflow)',
  'Dòng_tiền_ra_(Outflow)': 'Dòng tiền ra (Outflow)',
  'Trung_lập_(Neutral)': 'Trung lập (Neutral)',
} as const;
