/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */
import type { NarrativeMoneyCoinDtoVol } from './narrativeMoneyCoinDtoVol';
import type { NarrativeMoneyCoinDtoMcap } from './narrativeMoneyCoinDtoMcap';

export interface NarrativeMoneyCoinDto {
  vol: NarrativeMoneyCoinDtoVol;
  mcap: NarrativeMoneyCoinDtoMcap;
}
