/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * DTO for narrative money attraction insights

Response structure: A dictionary mapping narrative names to their attraction insights
Example:
{
    "ai": "Thu hút dòng tiền mạnh mẽ.",
    "defi": "Khiêm tốn.",
    "nft": "Yếu."
}
 */
export interface NarrativeMoneyAttractionDto {[key: string]: string}
