/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Network Economy Strength Enum - for categorizing network economy strength
 */
export type NetworkEconomyStrength = typeof NetworkEconomyStrength[keyof typeof NetworkEconomyStrength];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NetworkEconomyStrength = {
  Kinh_tế_network_mạnh: 'Kinh tế network mạnh',
  Kinh_tế_network_vừa_phải: 'Kinh tế network vừa phải',
  Kinh_tế_network_nhẹ: 'Kinh tế network nhẹ',
} as const;
