/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */
import type { VolumeShare } from './volumeShare';
import type { GrowthTrend } from './growthTrend';

/**
 * DTO for NFT project metrics
 */
export interface NftProjectDto {
  protocol: string;
  latest_value: number;
  percentage_of_total: number;
  percentage_change: number;
  volume_share_class: VolumeShare;
  growth_trend_class: GrowthTrend;
}
