/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Onchain Activity Assessment Enum
 */
export type OnchainActivityAssessment = typeof OnchainActivityAssessment[keyof typeof OnchainActivityAssessment];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OnchainActivityAssessment = {
  'Hoạt_động_on-chain_tốt,_adoption_&_thanh_khoản_mạnh': 'Hoạt động on-chain tốt, adoption & thanh khoản mạnh',
  'Hoạt_động_on-chain_trung_bình,_có_tín_hiệu_nhưng_chưa_mạnh_bền': 'Hoạt động on-chain trung bình, có tín hiệu nhưng chưa mạnh bền',
  'Hoạt_động_on-chain_yếu,_adoption_&_thanh_khoản_thấp': 'Hoạt động on-chain yếu, adoption & thanh khoản thấp',
} as const;
