/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Overall Growth Enum - for categorizing overall growth performance
 */
export type OverallGrowth = typeof OverallGrowth[keyof typeof OverallGrowth];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OverallGrowth = {
  Tăng_trưởng_tốt: 'Tăng trưởng tốt',
  Tăng_trưởng_không_tốt: 'Tăng trưởng không tốt',
} as const;
