/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */
import type { CryptoMarketState } from './cryptoMarketState';

export interface OverallMarketStateDto {
  crypto_market_state: CryptoMarketState;
  crypto_market_state_score: number;
  max_score: number;
  min_score: number;
}
