/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 🐺 Werewolf Betting Game API
 * API for Werewolf Betting Game with auto-play mode. WebSocket namespace: /game
 * OpenAPI spec version: 1.0.0
 */
import type { PlayerAliveDto } from './playerAliveDto';
import type { PlayerDeadDto } from './playerDeadDto';

export interface PlayersProgressDto {
  alive: PlayerAliveDto[];
  dead: PlayerDeadDto[];
}
