/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Price Level Enum - for detect_price_level function
 */
export type PriceLevel = typeof PriceLevel[keyof typeof PriceLevel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PriceLevel = {
  High: 'High',
  Medium: 'Medium',
  Low: 'Low',
} as const;
