/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */
import type { PriceTrend } from './priceTrend';

export interface PriceTrendDto {
  btc_close_avg_all_periods: number;
  btc_vol_avg_all_periods: number;
  btc_trend: PriceTrend;
  eth_close_avg_all_periods: number;
  eth_vol_avg_all_periods: number;
  eth_trend: PriceTrend;
}
