/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Price Trend Enum - for detect_price_trend function
 */
export type PriceTrend = typeof PriceTrend[keyof typeof PriceTrend];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PriceTrend = {
  Uptrend: 'Uptrend',
  Downtrend: 'Downtrend',
  Sideway: 'Sideway',
} as const;
