/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Primary Flow Enum
 */
export type PrimaryFlow = typeof PrimaryFlow[keyof typeof PrimaryFlow];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PrimaryFlow = {
  'Dòng_tiền_sơ_cấp_đang_vào_(Primary_inflow)': 'Dòng tiền sơ cấp đang vào (Primary inflow)',
  'Dòng_tiền_sơ_cấp_đang_rút_ra_(Primary_outflow)': 'Dòng tiền sơ cấp đang rút ra (Primary outflow)',
  'Dòng_tiền_sơ_cấp_trung_lập_(Neutral)': 'Dòng tiền sơ cấp trung lập (Neutral)',
} as const;
