/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */
import type { PrimaryFlow } from './primaryFlow';

export interface PrimaryFlowDto {
  primary_flow: PrimaryFlow;
  primary_flow_score: number;
  max_score: number;
  min_score: number;
}
