/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Viral Bot API
 * OpenAPI spec version: 0.0.12
 */
import type { ResponseHubEventDtoType } from './responseHubEventDtoType';

export interface ResponseHubEventDto {
  readonly id: number;
  readonly created_at: string;
  readonly updated_at: string;
  readonly type: ResponseHubEventDtoType;
  readonly hash: string;
  readonly timestamp: number;
  readonly blockNumber: number;
  readonly hubAddress: string;
  readonly tokenAddress: string;
  readonly userAddress: string;
  readonly amount: string;
  readonly payload: string;
  readonly claimId: string;
}
