/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Viral Bot API
 * OpenAPI spec version: 0.0.12
 */
import type { ResponseClaimingHistoryDtoClaimState } from './responseClaimingHistoryDtoClaimState';

export interface ResponseClaimingHistoryDto {
  readonly id: number;
  readonly created_at: string;
  readonly updated_at: string;
  readonly walletAddress: string;
  readonly claimState: ResponseClaimingHistoryDtoClaimState;
  readonly nonce: string;
  readonly claimedAmount: string;
  readonly claimTime: number;
}
