/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Viral Bot API
 * OpenAPI spec version: 0.0.12
 */

export interface ResponseClaimParamDto {
  readonly id: string;
  readonly chainId: string;
  readonly tokenAddress: string;
  readonly amount: string;
  readonly payload: string;
  readonly expiredBlockNumber: string;
  readonly signature: string;
  readonly adminAddress: string;
  readonly recipient: string;
}
