/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Viral Bot API
 * OpenAPI spec version: 0.0.12
 */

export type ResponseClaimingHistoryDtoClaimState = typeof ResponseClaimingHistoryDtoClaimState[keyof typeof ResponseClaimingHistoryDtoClaimState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResponseClaimingHistoryDtoClaimState = {
  pending: 'pending',
  completed: 'completed',
} as const;
