/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Viral Bot API
 * OpenAPI spec version: 0.0.12
 */

export type ResponseClaimingRequestDtoClaimState = typeof ResponseClaimingRequestDtoClaimState[keyof typeof ResponseClaimingRequestDtoClaimState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResponseClaimingRequestDtoClaimState = {
  pending: 'pending',
  completed: 'completed',
} as const;
