/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Viral Bot API
 * OpenAPI spec version: 0.0.12
 */
import type { MemeResponse } from './memeResponse';
import type { ResponseHubEventDto } from './responseHubEventDto';

export interface ResponseClaimingMemeDetailDto {
  readonly id: number;
  readonly created_at: string;
  readonly updated_at: string;
  readonly claimTime: number;
  readonly walletAddress: string;
  readonly tokenAddress: string;
  readonly claimAmount: string;
  readonly payload: string;
  readonly nonce: string;
  readonly memeInfo: MemeResponse;
  readonly eventInfo: ResponseHubEventDto;
}
