/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */
import type { RwaShare } from './rwaShare';
import type { GrowthTrend } from './growthTrend';

/**
 * DTO for RWA project metrics
 */
export interface RwaProjectDto {
  protocol: string;
  latest_value: number;
  value_share: number;
  percentage_change: number;
  rwa_share_class: RwaShare;
  growth_trend_class: GrowthTrend;
}
