/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * RWA Share Enum - for categorizing RWA value share
 */
export type RwaShare = typeof RwaShare[keyof typeof RwaShare];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RwaShare = {
  Chiếm_lĩnh_RWA: 'Chiếm lĩnh RWA',
  Đáng_quan_tâm: 'Đáng quan tâm',
  Nhỏ: 'Nhỏ',
} as const;
