/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Simple Growth Enum - for basic growth categorization
 */
export type SimpleGrowth = typeof SimpleGrowth[keyof typeof SimpleGrowth];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SimpleGrowth = {
  Tăng_trưởng_mạnh: 'Tăng trưởng mạnh',
  Tăng_trưởng_nhẹ: 'Tăng trưởng nhẹ',
} as const;
