/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

export type SpotExchange = typeof SpotExchange[keyof typeof SpotExchange];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SpotExchange = {
  Cex: 'Cex',
  Dex: 'Dex',
  Total: 'Total',
} as const;
