/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */
import type { SimpleGrowth } from './simpleGrowth';
import type { AdoptionLevel } from './adoptionLevel';

/**
 * DTO for Stablecoin project metrics
 */
export interface StablecoinProjectDto {
  protocol: string;
  latest_outstanding_supply: number;
  outstanding_share: number;
  percentage_change_transfer_count: number;
  percentage_change_transfer_vol: number;
  growth_class: SimpleGrowth;
  adoption_class: AdoptionLevel;
}
