/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

export type SupportedNarrative = typeof SupportedNarrative[keyof typeof SupportedNarrative];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SupportedNarrative = {
  rwa: 'rwa',
  ai: 'ai',
  defi: 'defi',
  nft: 'nft',
  l2: 'l2',
  privacy: 'privacy',
  gaming: 'gaming',
  restaking: 'restaking',
  'liquid-staking': 'liquid-staking',
  us: 'us',
  meme: 'meme',
  depin: 'depin',
  lending: 'lending',
  'top-20-cmc': 'top-20-cmc',
} as const;
