/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

export type SupportedOverallMetrics = typeof SupportedOverallMetrics[keyof typeof SupportedOverallMetrics];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SupportedOverallMetrics = {
  tvl: 'tvl',
  protocols: 'protocols',
  totalVolume24h: 'totalVolume24h',
  totalFees24h: 'totalFees24h',
  totalRevenue24h: 'totalRevenue24h',
  users: 'users',
  totalAppRevenue24h: 'totalAppRevenue24h',
  bridgedTvl: 'bridgedTvl',
} as const;
