/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

export type SupportedAssets = typeof SupportedAssets[keyof typeof SupportedAssets];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SupportedAssets = {
  SPX: 'SPX',
  DXY: 'DXY',
  XAUUSD: 'XAUUSD',
  US10Y: 'US10Y',
  USIRYY: 'USIRYY',
  FEDFUNDS: 'FEDFUNDS',
  M2SL: 'M2SL',
  M2V: 'M2V',
  WALCL: 'WALCL',
} as const;
