/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

export type SupportedStablecoinMetrics = typeof SupportedStablecoinMetrics[keyof typeof SupportedStablecoinMetrics];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SupportedStablecoinMetrics = {
  stablesMcap: 'stablesMcap',
  bridgedTo: 'bridgedTo',
  minted: 'minted',
  dominant: 'dominant',
} as const;
