/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

export type Total = typeof Total[keyof typeof Total];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Total = {
  TOTAL: 'TOTAL',
  TOTAL2: 'TOTAL2',
  TOTAL3: 'TOTAL3',
} as const;
