/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Viral Bot API
 * OpenAPI spec version: 0.0.12
 */
import type { UserResponseVerifiedType } from './userResponseVerifiedType';

export interface UserResponse {
  readonly id: number;
  readonly created_at: string;
  readonly updated_at: string;
  readonly walletAddress: string;
  readonly xUserId: string;
  readonly name: string;
  readonly username: string;
  readonly verified: string;
  readonly verifiedType: UserResponseVerifiedType;
  readonly image: string;
  readonly totalEarnedAmount: string;
  readonly totalClaimed: string;
}
