/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Viral Bot API
 * OpenAPI spec version: 0.0.12
 */

export type UserResponseVerifiedType = typeof UserResponseVerifiedType[keyof typeof UserResponseVerifiedType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserResponseVerifiedType = {
  none: 'none',
  blue: 'blue',
  government: 'government',
  business: 'business',
} as const;
