/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Viral Bot API
 * OpenAPI spec version: 0.0.12
 */

export interface UserEarningAmountResponse {
  readonly totalEarnedAmount: string;
  readonly totalClaimedAmount: string;
  readonly availableToClaimAmount: string;
}
