/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Valuation Label Enum - for compute_valuation_score function
 */
export type ValuationLabel = typeof ValuationLabel[keyof typeof ValuationLabel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ValuationLabel = {
  Overvalued: 'Overvalued',
  Neutral: 'Neutral',
  Undervalued: 'Undervalued',
} as const;
