/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */
import type { ValuationLabel } from './valuationLabel';

export interface ValuationScoreDto {
  valuation_score: number;
  max_score: number;
  min_score: number;
  valuation_level: ValuationLabel;
}
