/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AMR API
 * API for Automatic Fundamental Market Report
 * OpenAPI spec version: 1.0.0
 */

/**
 * Volume Share Enum - for categorizing volume/share percentage
 */
export type VolumeShare = typeof VolumeShare[keyof typeof VolumeShare];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VolumeShare = {
  Chiếm_lĩnh: 'Chiếm lĩnh',
  Đáng_quan_tâm: 'Đáng quan tâm',
  Nhỏ: 'Nhỏ',
} as const;
